import pandas as pd
import numpy as np
df=pd.read_csv('digital_behaviour_data.csv')
# print(df)
print(df.head(5))
print(df.tail(5))
print(df.shape)
print(df.columns)
print(df.describe())
print(df.info())
print(df['Instagram_Minutes'])
print(df[['Date','Instagram_Minutes']])
print(df['Instagram_Minutes'].sum())
print(df['Study_Minutes'].mean())
print(df['YouTube_Minutes'].max())
print(df[df['Instagram_Minutes']>100])
print(df[df['Study_Minutes']>180])
print(df[df['Instagram_Minutes']>df['Study_Minutes']])
print(df['Instagram_Minutes'].sort())